name: task_mate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  msh_checkbox: ^2.0.1
  easy_date_timeline: ^1.0.5
  lottie: ^2.7.0
  dots_indicator: ^3.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  get_storage: ^2.1.1
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

