// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkErN15-1F__wRi4P4kZC7fEFQBYOQ86A',
    appId: '1:355020685950:web:d8522e0549cfc87b1b0e2f',
    messagingSenderId: '355020685950',
    projectId: 'task-mate-294f1',
    authDomain: 'task-mate-294f1.firebaseapp.com',
    storageBucket: 'task-mate-294f1.appspot.com',
    measurementId: 'G-SN0WJD6BC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YT7cMHw7TsCein6Ka950tWby_fpjQZM',
    appId: '1:355020685950:android:559a66ebe65df9511b0e2f',
    messagingSenderId: '355020685950',
    projectId: 'task-mate-294f1',
    storageBucket: 'task-mate-294f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtQ1w3-zTdjV7My1jb93JpfV5jNpMWPPM',
    appId: '1:355020685950:ios:7d25321117c3c3201b0e2f',
    messagingSenderId: '355020685950',
    projectId: 'task-mate-294f1',
    storageBucket: 'task-mate-294f1.appspot.com',
    iosBundleId: 'com.example.taskMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtQ1w3-zTdjV7My1jb93JpfV5jNpMWPPM',
    appId: '1:355020685950:ios:6cb011a6dd4211f01b0e2f',
    messagingSenderId: '355020685950',
    projectId: 'task-mate-294f1',
    storageBucket: 'task-mate-294f1.appspot.com',
    iosBundleId: 'com.example.taskMate.RunnerTests',
  );
}
